export const config = {
  port: process.env.PORT || 3001,
  mercadopagoAccessToken: process.env.MERCADOPAGO_ACCESS_TOKEN,
  mercadopagoWebhookSecret: process.env.MERCADOPAGO_WEBHOOK_SECRET,
  mercadopagoClientId: process.env.MERCADOPAGO_CLIENT_ID,
  mercadopagoClientSecret: process.env.MERCADOPAGO_CLIENT_SECRET,
  frontendUrl: process.env.FRONTEND_URL || "http://localhost:5173",
  backendUrl: process.env.BACKEND_URL || "http://localhost:3001",
  adminUrl: process.env.ADMIN_URL || "http://localhost:5174",
  emailEnabled: process.env.EMAIL_ENABLED === "true",
  resendApiKey: process.env.RESEND_API_KEY,
  resendTemplatePaidId: process.env.RESEND_TEMPLATE_PAID_ID,
  emailFrom: process.env.EMAIL_FROM,
  emailFromName: process.env.EMAIL_FROM_NAME || "Home Pisos Vinílicos",
};
